<a href="https://colab.research.google.com/github/kunji1999/Data-Science/blob/main/exp22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



dot product


In [ ]:
import numpy as np

A = [[12, 7, 3], [4, 5, 6], [7, 8, 9]]
B = [[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]]

result= [[0,0,0,0], [0,0,0,0], [0,0,0,0]]
result= np.dot(A,B)

for p in result:
    print(p)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]





Element wise multiplication


In [ ]:
import numpy as np
in_arr1=np.matrix([[2, -7, 5], [-6, 2, 0]])
in_arr2 = np.matrix([[0, -7, 8], [5, -2, 9]])
	
print ("1st Input array : ", in_arr1)
print ("2nd Input array : ", in_arr2)

out_arr=np.array(in_arr1)*np.array(in_arr2)
print ("Resultant output array: ", out_arr)


1st Input array :  [[ 2 -7  5]
 [-6  2  0]]
2nd Input array :  [[ 0 -7  8]
 [ 5 -2  9]]
Resultant output array:  [[  0  49  40]
 [-30  -4   0]]


Vectorised Sum

In [1]:
import numpy as np
arr2 = np.array([1, 2, 3])
s = np.sum(arr2)  
print(s)  

6


Outer product

In [ ]:
import numpy as np
x = np.array([1, 4, 0], float)
y = np.array([2, 2, 1], float)
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)
print("Outer product of x and y:")
print(np.outer(x, y))


Matrices and vectors.
x:
[1. 4. 0.]
y:
[2. 2. 1.]
Outer product of x and y:
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]


B. transpose of a matrix

In [ ]:
import numpy as np
gfg = np.matrix('[4, 1; 12, 3]')
geek = gfg.transpose()
print(geek)

[[ 4 12]
 [ 1  3]]


single value decomposition.

In [ ]:

from numpy import array
from scipy.linalg import svd

A = array([[1, 2], [3, 4], [5, 6]])
print(A)
U, s, VT = svd(A)
print(U)
print(s)
print(VT)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
